version: 1
disable_existing_loggers: false

formatters:
  simple_jst:
    class: zangetsu_logger.formatters.zangetsuConsoleFormatter
    format: '%(jst_time)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s'
  json:
    class: zangetsu_logger.formatters.zangetsuJsonFormatter
    # JSONフォーマッターでファイル名と行番号を含めるための設定
    # 通常は追加フィールドとして設定されます

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple_jst
    stream: ext://sys.stdout
  
  file:
    class: zangetsu_logger.handlers.EnvVarFileHandler
    level: DEBUG
    formatter: json
    filename: zangetsu_app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  error_file:
    class: zangetsu_logger.handlers.EnvVarFileHandler
    level: ERROR
    formatter: json
    filename: zangetsu_error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  zangetsu:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: no

root:
  level: DEBUG
  handlers: [console]
  propagate: no