version: 1
disable_existing_loggers: false

formatters:
  simple_jst:
    class: senju3_logger.formatters.Senju3ConsoleFormatter
    format: '%(jst_time)s - %(name)s - %(levelname)s - %(message)s'
  json:
    class: senju3_logger.formatters.Senju3JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple_jst
    stream: ext://sys.stdout
  
  file:
    class: senju3_logger.handlers.EnvVarFileHandler
    level: DEBUG
    formatter: json
    filename: senju3_app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  error_file:
    class: senju3_logger.handlers.EnvVarFileHandler
    level: ERROR
    formatter: json
    filename: senju3_error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  senju3:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: no

root:
  level: DEBUG
  handlers: [console]
  propagate: no